#####################################################################################################################################################################################
#####################################################################################################################################################################################
##                                                                                                                                                                                 ##
##       ___           ___           ___           ___           ___           ___           ___                       ___                    ___           ___           ___      ##
##      /\  \         /\  \         /\  \         /\  \         /\__\         /\  \         /\  \          ___        /\  \                  /\  \         /\  \         /\  \     ##
##     /::\  \       /::\  \       /::\  \        \:\  \       /:/  /        /::\  \        \:\  \        /\  \      /::\  \                /::\  \       /::\  \        \:\  \    ##
##    /:/\:\  \     /:/\:\  \     /:/\ \  \        \:\  \     /:/__/        /:/\:\  \        \:\  \       \:\  \    /:/\:\  \              /:/\:\  \     /:/\:\  \        \:\  \   ##
##   /::\~\:\  \   /::\~\:\  \   _\:\~\ \  \       /::\  \   /::\  \ ___   /::\~\:\  \       /::\  \      /::\__\  /:/  \:\  \            /::\~\:\__\   /:/  \:\  \       /::\  \  ##
##  /:/\:\ \:\__\ /:/\:\ \:\__\ /\ \:\ \ \__\     /:/\:\__\ /:/\:\  /\__\ /:/\:\ \:\__\     /:/\:\__\  __/:/\/__/ /:/__/ \:\__\          /:/\:\ \:|__| /:/__/ \:\__\     /:/\:\__\ ##
##  \/__\:\/:/  / \:\~\:\ \/__/ \:\ \:\ \/__/    /:/  \/__/ \/__\:\/:/  / \:\~\:\ \/__/    /:/  \/__/ /\/:/  /    \:\  \  \/__/          \:\~\:\/:/  / \:\  \ /:/  /    /:/  \/__/ ##
##       \::/  /   \:\ \:\__\    \:\ \:\__\     /:/  /           \::/  /   \:\ \:\__\     /:/  /      \::/__/      \:\  \                 \:\ \::/  /   \:\  /:/  /    /:/  /      ##
##       /:/  /     \:\ \/__/     \:\/:/  /     \/__/            /:/  /     \:\ \/__/     \/__/        \:\__\       \:\  \                 \:\/:/  /     \:\/:/  /     \/__/       ##
##      /:/  /       \:\__\        \::/  /                      /:/  /       \:\__\                     \/__/        \:\__\                 \::/__/       \::/  /                  ##
##      \/__/         \/__/         \/__/                       \/__/         \/__/                                   \/__/                  ~~            \/__/                   ##
##                                                                                                                                                                                 ##
#####################################################################################################################################################################################
#####################################################################################################################################################################################

# [!] Disclaimer
# File not useful yet.
# This is just to plan out the layout.
# There are plans to make a lang file.

############################################
#                                          #
#   Bot Config                             #
#                                          #
############################################
# Bot Token in an .env file for safety...  #
# Learn more in README.md                  #
############################################
Prefix: "-"

Embeds:
  Color:
    Default: WHITE
    Warn: ORANGE
    Error: RED
  Footer:
    Text: Aesthetic BOT
    Icon: https://i.imgur.com/wz6faLJ.jpg

# More to come...

############################################
#                                          #
#   Console Customisation                  #
#                                          #
############################################
ConsoleStyle:
  Prefix:
    Info: INFO >
    Warn: WARN >
    Error: ERROR >

# [!] Not implemented yet
ConsoleOutput:
  Log:
    Messages: false
    VoiceChannels: false
    CommandsRan: false
    InvalidCommands: false
    BotActions: false